CREATE TABLE products (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sku VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 100),
  stock INTEGER NOT NULL CHECK (stock BETWEEN 0 AND 1000000),
  CONSTRAINT sku_format CHECK (sku ~ '^[A-Z0-9-]{1,30}$')
);
